"""Minimal FastAPI service.

This module creates the web application and defines its routes.
"""

# Import FastAPI for the application, HTTPException for API errors, and status
# for readable HTTP status codes.
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel


# Call the FastAPI constructor, similar to creating a Spring application
# context in Java. The title appears in the generated API documentation.
app = FastAPI(title="FastAPI Service")


# Register the function below for HTTP GET requests to the root path "/".
# This is similar to Spring's @GetMapping("/") annotation.
@app.get("/")
def read_root() -> dict[str, str]:
    # self is not needed here because this is a function, not a class method.
    """Return a welcome message."""
    # FastAPI converts this Python dictionary into a JSON response with
    # HTTP status 200. dict[str, str] means string keys and string values.
    return {"message": "FastAPI service is running"}

@app.get("/health")
def health_check() -> dict[str, str]:
    # A lightweight health endpoint is useful for monitoring and deployment
    # checks because it confirms that the service can receive requests.
    """Return service health status."""
    return {"status": "ok"}


class TaskCreate(BaseModel):
    """Fields required when creating or updating a task."""

    # Pydantic validates the incoming JSON and rejects missing or wrong types.
    title: str
    description: str = ""


class Task(TaskCreate):
    """A task returned by the API, including its generated ID."""

    # The API adds these fields when it creates a task.
    id: int
    completed: bool = False


# This list is intentionally in memory for learning. Data is lost when the
# server restarts; a database would be used in a production service.
tasks: list[Task] = []


def find_task(task_id: int) -> Task:
    """Find a task or raise the standard API 404 response."""
    # Endpoint functions reuse this helper so every lookup has the same
    # not-found behavior instead of duplicating the loop and error response.
    for task in tasks:
        if task.id == task_id:
            return task
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Task {task_id} not found",
    )


@app.get("/tasks", response_model=list[Task])
def list_tasks() -> list[Task]:
    # response_model tells FastAPI to serialize each Task consistently.
    """Return all tasks."""
    return tasks


@app.post("/tasks", response_model=Task, status_code=status.HTTP_201_CREATED)
def create_task(task_data: TaskCreate) -> Task:
    # FastAPI builds task_data from the request JSON before this function runs.
    """Create a task from the validated JSON request body."""
    # IDs are generated by the application so clients do not choose them.
    task = Task(
        id=len(tasks) + 1,
        title=task_data.title,
        description=task_data.description,
    )
    # Appending changes the in-memory collection used by later requests.
    tasks.append(task)
    return task


@app.get("/tasks/{task_id}", response_model=Task)
def get_task(task_id: int) -> Task:
    # FastAPI converts the URL value to int and returns 422 if conversion
    # fails. The helper then returns the task or a 404 response.
    """Return one task by its integer ID."""
    return find_task(task_id)


@app.put("/tasks/{task_id}", response_model=Task)
def update_task(task_id: int, task_data: TaskCreate) -> Task:
    # This endpoint replaces the editable fields while keeping the ID and
    # completion state already stored on the task.
    """Replace the title and description of an existing task."""
    task = find_task(task_id)
    task.title = task_data.title
    task.description = task_data.description
    return task


@app.delete("/tasks/{task_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_task(task_id: int) -> None:
    # A successful delete returns no response body, represented by HTTP 204.
    """Delete a task and return an empty 204 response."""
    task = find_task(task_id)
    tasks.remove(task)